---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  commands:
  - export BUILD_MODE=MOCK
  - export CARGO_HOME=$PWD/drone/cargo
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - ./integration-tests/build.sh

- name: integration-tests
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  commands:
  - export BUILD_MODE=MOCK
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - export PYTHON_VENV_DIR=$PWD/drone/venv
  - ./integration-tests/run.sh

- name: teardown
  image: cryptocom/chain-test:latest
  pull: if-not-exists
  commands:
  - ./integration-tests/cleanup.sh
  when:
    status:
      - success
      - failure

volumes:
  - name: sgx
    host:
      path: /dev/sgx

trigger:
  branch:
  - master
  - staging
  - trying
  event:
  - push

...
