[package]
name = "cro-nodelib"
version = "0.1.0"
edition = "2018"
authors = ["Calvin Lau <calvin@crypto.com>"]
license = "Apache-2.0"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[features]
mock = []

[lib]
name = "cro_nodelib"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.3.3"

[dependencies]
neon = "0.3.3"
hex = "0.4.0"
parity-scale-codec = { features = ["derive"], version = "1.1" }
chain-core = { git = "https://github.com/calvinlauco/chain", rev = "36b77c82bb54d4412da23d84557477294928c1f0" }
client-common = { git = "https://github.com/calvinlauco/chain", rev = "36b77c82bb54d4412da23d84557477294928c1f0" }
client-core = { git = "https://github.com/calvinlauco/chain", rev = "36b77c82bb54d4412da23d84557477294928c1f0" }
